Umbraco2/Controllers/MemberSurfaceController.cs
using System;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Web.Mvc;
using Umbraco2.Models;

namespace Umbraco2.Controllers
{
    public class MemberSurfaceController : SurfaceController
    {

      
        [System.Web.Http.HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model)
        {
            if (User.Identity.IsAuthenticated)
            {
                return CurrentUmbracoPage();
            }

            //System.Web.Helpers.AntiForgery.Validate();

            if (ModelState.IsValid && Membership.ValidateUser(model.Username, model.Password))
            {
                Response.Cookies.Remove(FormsAuthentication.FormsCookieName);
                FormsAuthentication.SetAuthCookie(model.Username, false);
                return Redirect("/Login"); //return Redirect("/Private_Content");
           
            }

            // If we got this far, something failed, redisplay form
            ModelState.AddModelError("LoginError", "The user name or password provided is incorrect.");
            return Redirect("/Login");
        }

     
        public ActionResult LogOut()
        {
            Session.Clear();
            Session.Abandon();

            Response.Cache.SetExpires(DateTime.UtcNow.AddMinutes(-1));
            Response.Cache.SetCacheability(HttpCacheability.NoCache);
            Response.Cache.SetNoStore();

            Response.Cookies.Clear();

            FormsAuthentication.SignOut();
            //WebSecurity.Logout();

            return Redirect("/Login");          
        }

    }
}

Umbraco2/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}

@if (!User.Identity.IsAuthenticated)
{
    <h2>Login Page</h2>
    <div id="loginForm">
        @Html.Partial("LoginPartial", new Umbraco2.Models.LoginModel())
    </div>
}
else
{
    <h3>Welcome @Members.GetCurrentMemberProfileModel().UserName !</h3>
    <h3> @Html.ActionLink("Logga ut", "LogOut", "MemberSurface", null, new { @class = "btn btn-success logout " })</h3>
}

Umbraco2/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = null;
    var hl = Model.GetPropertyValue<IPublishedContent>("headerLogo");
    
    //var logoUrl = hl.Url;
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
    <link href="Content/bootstrap.css" type="text/css" rel="stylesheet" />
    <link href="Template/css/site.css" type="text/css" rel="stylesheet"/>
    <script src="Scripts/bootstrap.js"></script>

    @*<script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.8.0/fullcalendar.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.8.0/fullcalendar.min.css"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.8.0/fullcalendar.print.css"></script>*@
    


</head>
<body>
  <div class="header">
    <div class="header1">@Umbraco.Field("headerString")
     @*<img src="@logoUrl" />*@
    </div>
  </div>
  <div>
    @RenderBody()
  </div>
</body>
</html>

Umbraco2/Views/News.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

Umbraco2/Views/Our_Aircrafts.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

Umbraco2/Views/Our_Destinations.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
                

Umbraco2/Views/Private_Content.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = "Master.cshtml";
}


@if (User.Identity.IsAuthenticated)
{
    <h3>Welcome @Members.GetCurrentMemberProfileModel().UserName !</h3>
    <h3> @Html.ActionLink("Logga ut", "LogOut", "MemberSurface", null, new { @class = "btn btn-success logout " })</h3>

}

Umbraco2/Views/StartPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoViewPage
@{
    Layout = "Master.cshtml";
    var clickImage1 = Model.GetPropertyValue<IPublishedContent>("link_with_Image1");   //@Umbraco.Field("clickable_Image_Link1")
    var url1 = clickImage1.GetPropertyValue<string>("url");
    var image1 = clickImage1.GetPropertyValue<IPublishedContent>("image");
    var imgSrc1 = image1.Url;
    var descript1 = clickImage1.GetPropertyValue<string>("linkDescription");

    var clickImage2 = Model.GetPropertyValue<IPublishedContent>("link_with_Image2");   //@Umbraco.Field("clickable_Image_Link1")
    var url2 = clickImage2.GetPropertyValue<string>("url");
    var image2 = clickImage2.GetPropertyValue<IPublishedContent>("image");
    var imgSrc2 = image2.Url;
    var descript2 = clickImage2.GetPropertyValue<string>("linkDescription");

    var clickImage3 = Model.GetPropertyValue<IPublishedContent>("link_with_Image3");   //@Umbraco.Field("clickable_Image_Link1")


    var url3 = clickImage3.GetPropertyValue<string>("url");
    var image3 = clickImage3.GetPropertyValue<IPublishedContent>("image");
    var imgSrc3 = image3.Url;
    var descript3 = clickImage3.GetPropertyValue<string>("linkDescription");

    var loginString = Model.GetPropertyValue("startPageLoginString");
    var loginUrl = Model.GetPropertyValue("startPageLoginUrl");



}
@*<div class="header">
    <div class="header1">@Umbraco.Field("headerstring")
        <img src="@logoUrl" />
    </div>
</div>*@

<h2 class="special">@Umbraco.Field("editableDescription")</h2>
<div>
    <a id="loginLink" href="@loginUrl">@loginString</a>
</div>
<div class="puffs_startpage">
    <a id="a1" href="@url1">
      <div>@descript1<img src="@imgSrc1" /></div>  
    </a>

    <a id="a2" href="@url2">
        <div>@descript2<img src="@imgSrc2" /></div>
    </a>
    
    <a id="a3" href="@url3">
        <div>@descript3<img src="@imgSrc3" /></div>  
    </a>
</div>